{
    "name": "Ventas e Inventario",
    "summary": "Inventario, ventas, gastos, reinversión y control de caja",
    "version": "19.0.1.13.0",
    "category": "Sales",
    "author": "Custom",
    "license": "LGPL-3",
    "depends": ["base", "web", "mail"],
    "data": [
        "security/ir.model.access.csv",
        "data/sequences.xml",
        "data/dashboard.xml",
        "report/product_catalog_report.xml",
        "views/product_views.xml",
        "views/sale_views.xml",
        "views/expense_views.xml",
        "views/recovery_views.xml",
        "views/dashboard_views.xml",
        "views/inventory_review_views.xml",
        "views/menu_views.xml",
    ],
    "application": True,
    "installable": True,
    "assets": {
        "web.assets_backend": [
            "sales_inventory/static/src/scss/dashboard.scss",
            "sales_inventory/static/src/js/image_crop_field.js",
            "sales_inventory/static/src/xml/image_crop_field.xml",
            "sales_inventory/static/src/js/inventory_review.js",
            "sales_inventory/static/src/xml/inventory_review.xml",
            "sales_inventory/static/src/js/dashboard.js",
            "sales_inventory/static/src/xml/dashboard.xml",
        ],
    },
}
